### ISSUE TITLE
Rounding of button

### ISSUE THREAD

**Issue by Cortez2002** [1Kxhu/CuoreUI#12]
Hi!

When i round a button with more than: 8, lets say: 20 and have a black backgound in Form, i get an gray edge outlining as shown in the image.
I dont know if this is a bug or its me that dont understand how to get rid of it.

![Rounded button](https://github.com/user-attachments/assets/f2c14d43-df11-42aa-a13a-1a2437d41f4d)

**Comment by 1Kxhu** [comment]
Are you using WinForms .net, or WinForms _**.NET Framework**_?
 - `WinForms .NET Framework is the targeted winforms version by this library.`

I cannot replicate this issue.
Maybe it is your problem with what _**BackColor**_ the button uses?

Tested CuoreUI.Winforms [2024.11.2](https://www.nuget.org/packages/CuoreUI.Winforms/2024.11.2):
![image](https://github.com/user-attachments/assets/e573bba2-cef6-43a9-836a-36ebf2e56597)

**Comment by Cortez2002** [comment]
I found out that it only occured when i used the Darkmode script from: https://github.com/BlueMystical/Dark-Mode-Forms.
So my bad in a way.

**Comment by 1Kxhu** [comment]
relieved to see its not my fault, enjoy
